# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /

spring:
  profiles:
      active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.129.161:3306/csmp
    username: root
    password: root

security:
  basic:
    enabled: false