# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
logging:
  path: /log
  level:
      root: INFO

authorization.excludePaths:
  - /
  - /index
  - /login
  - /logout
  - /error
  - /info
  - /swagger-ui.html
  - /swagger-resources/**
  - /v2/api-docs
  - /users